"""add_contest_visibility

Revision ID: 37f7f5b28b9c
Revises: bb21ea6eb23e
Create Date: 2026-02-18 13:22:06.892838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37f7f5b28b9c'
down_revision: Union[str, Sequence[str], None] = 'bb21ea6eb23e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contests', sa.Column('is_visible', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contests', 'is_visible')
    # ### end Alembic commands ###
