"""add_problem_stats

Revision ID: 67b6dc0f1450
Revises: 6631e621d88e
Create Date: 2026-02-17 15:22:47.882272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67b6dc0f1450'
down_revision: Union[str, Sequence[str], None] = '6631e621d88e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('accepted_count', sa.Integer(), nullable=True))
    op.add_column('problems', sa.Column('submission_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'submission_count')
    op.drop_column('problems', 'accepted_count')
    # ### end Alembic commands ###
