"""Add group and points to test_cases

Revision ID: ad8d8755a148
Revises: ac7150079b95
Create Date: 2026-02-23 16:55:06.004858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad8d8755a148'
down_revision: Union[str, Sequence[str], None] = 'ac7150079b95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_cases', sa.Column('group', sa.Integer(), nullable=True))
    op.add_column('test_cases', sa.Column('points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_cases', 'points')
    op.drop_column('test_cases', 'group')
    # ### end Alembic commands ###
