"""fix_stats_nullable

Revision ID: bb21ea6eb23e
Revises: 67b6dc0f1450
Create Date: 2026-02-17 15:30:20.143589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb21ea6eb23e'
down_revision: Union[str, Sequence[str], None] = '67b6dc0f1450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE problems SET accepted_count = 0 WHERE accepted_count IS NULL")
    op.execute("UPDATE problems SET submission_count = 0 WHERE submission_count IS NULL")
    op.alter_column('problems', 'accepted_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               server_default='0')
    op.alter_column('problems', 'submission_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               server_default='0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('problems', 'submission_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('problems', 'accepted_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
